# logstash.yml
################################################################################
# Version: 22.04                                                               #
# Required: Yes (DOCKER ONLY)                                                  #
# Description: This is a required file for a Docker installation               #
#                                                                              #
################################################################################
#
http.host: "0.0.0.0"
#path.config: /usr/share/logstash/pipeline/pipelines.yml

config.reload.automatic: ${LOGSTAST_RELOAD_AUTOMATIC:true}
elasticsearch.hosts:
  [
    "${ELASTICSEARCH_PROTOCOL:https}://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}",
  ]
elasticsearch.username: ${ELASTICSEARCH_USERNAME:logstash_system}
elasticsearch.password: ${ELASTICSEARCH_PASSWORD:}
elasticsearch.ssl.verificationmode: ${ELASTICSEARCH_SSL_VERIFICATIONMODE:none}

xpack.monitoring.enabled: ${XPACK_MONITORING_ENABLED:true}
xpack.monitoring.elasticsearch.hosts: ${ELASTICSEARCH_PROTOCOL:https}://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}
xpack.monitoring.elasticsearch.username: ${ELASTICSEARCH_USERNAME:logstash_system}
xpack.monitoring.elasticsearch.password: ${ELASTICSEARCH_PASSWORD:}
