version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  apm-server:
    image: docker.elastic.co/apm/apm-server:${VERSION:-8.2.0}
    env_file: .env
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
      # labels:
      #   - traefik.enable=true
      #   - traefik.docker.lbswarm=true
      #   - traefik.docker.network=proxy
      #   - traefik.http.routers.apm.entrypoints=https
      #   - traefik.http.routers.apm.rule=Host(`${DOMAIN?domain variable not set}`)
      #   - traefik.http.routers.apm.tls=true
      #   - traefik.http.routers.apm.service=apm
      #   - traefik.http.services.apm.loadbalancer.server.scheme=${PROTOCOL:-http}
      #   - traefik.http.services.apm.loadbalancer.server.port=${PORT:-8200}
      #   - traefik.http.routers.apm.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    # ports:
    #   - target: 8200
    #     published: ${PORT:-8200}
    #     protocol: tcp
    #     mode: host
    environment:
      ES_JAVA_OPTS: -Xms${ELK_MEM_USE_GB:-1g} -Xmx${ELK_MEM_USE_GB:-1g}
      network.host: 0.0.0.0
      ELASTICSEARCH_PROTOCOL: ${ELASTICSEARCH_PROTOCOL:-http}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST:-elasticsearch}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT:-9200}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME:-elastic}
      KIBANA_PROTOCOL: ${KIBANA_PROTOCOL:-http}
      KIBANA_HOST: ${KIBANA_HOST:-kibana}
      KIBANA_PORT: ${KIBANA_PORT:-5601}
      KIBANA_USERNAME: ${KIBANA_USERNAME:-elastic}
      SSL_VERIFICATION_MODE: ${SSL_VERIFICATION_MODE:-none}
    configs:
      - source: apm_config
        target: /usr/share/apm-server/apm-server.yml
        mode: 0440
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      # default: {}
      proxy: {}
      elasticsearch: {}
      kibana: {}
    restart: always
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' -k --fail --silent --output /dev/null ${PROTOCOL:-http}://localhost:${PORT:-8200}/

################################################################################
################################################################################
################################################################################
networks:
  # default:
  #   driver: ${NETWORK_MODE:-bridge}
  #   attachable: true
  proxy:
    external: true
  elasticsearch:
    name: ${ELASTICSEARCH_NETWORK_NAME:-elasticsearch}
    external: true
  kibana:
    name: ${KIBANA_NETWORK_NAME:-kibana}
    external: true

configs:
  apm_config:
    file: $PWD/config/apm-server.yml
