network.host: 0.0.0.0
discovery.type: single-node
node.name: elasticsearch-docker-default-1
cluster.name: elasticsearch-docker-cluster
bootstrap.memory_lock: true
node.store.allow_mmap: false
ingest.geoip.downloader.enabled: false

xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.authc.token.enabled: true
xpack.security.audit.enabled: true
xpack.security.authc.realms.file.file1.order: 0
xpack.security.authc.realms.native.native1.order: 1
xpack.security.authc.api_key.enabled: true

xpack.security.http.ssl.key: certs/elasticsearch_node.key
xpack.security.http.ssl.certificate: certs/elasticsearch_node.crt

xpack.security.transport.ssl.key: certs/elasticsearch_node.key
xpack.security.transport.ssl.certificate: certs/elasticsearch_node.crt

xpack.http.ssl.verification_mode: certificate # certificate | none
xpack.security.http.ssl.verification_mode: certificate # certificate | none
xpack.security.transport.ssl.verification_mode: certificate # certificate | none

xpack.license.self_generated.type: basic # basic | trial
action.destructive_requires_name: false
