# logstash.yml
################################################################################
# Version: 21.03                                                               #
# Required: Yes (DOCKER ONLY                                                   #
# Description: This is a required file for a Docker installation               #
#                                                                              #
################################################################################
#
http.host: "0.0.0.0"
#path.config: etc/pfelk/logstash/pipeline/pipelines.yml

config.reload.automatic: true
elasticsearch.hosts: [https://elasticsearch:9200]
elasticsearch.username: logstash_system
elasticsearch.password: ""

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: [https://elasticsearch:9200]
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: ""
