# pipelines.yml
################################################################################
# Version: 22.01                                                               #
# Required: Yes                                                                #
# Description: This is a required file for a pfelk installation                #
# This file is where you define your pipelines. You can define multiple.       #
# For more information on multiple pipelines, see the documentation:           #
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html   #
#                                                                              #
################################################################################
#
- pipeline.id: pfelk
  path.config: "/etc/pfelk/conf.d/*.conf"
#  pipeline.ecs_compatibility: v1

# - pipeline.id: main
#  path.config: "/etc/logstash/conf.d/*.conf"
