---
version: "3.8"

services:
  ######################################################################################
  ######################################################################################
  ######################################################################################
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:${ELASTICSEARCH_VERSION:-7.14.1}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE}"
      restart_policy:
        condition: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    ports:
      - target: 8220
        published: 8220
        mode: host
    environment:
      ES_JAVA_OPTS: -Xms${ELK_MEM_USE_GB:-1g} -Xmx${ELK_MEM_USE_GB:-1g}
      network.host: 0.0.0.0

      FLEET_SERVER_ENABLE: ${FLEET_SERVER_ENABLE:-true}
      FLEET_SERVER_ELASTICSEARCH_HOST: ${ELASTICSEARCH_PROTOCOL:-http}://${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      FLEET_SERVER_SERVICE_TOKEN: ${FLEET_SERVER_SERVICE_TOKEN}
      FLEET_SERVER_POLICY: ${FLEET_SERVER_POLICY}
      FLEET_SERVER_INSECURE_HTTP: ${FLEET_SERVER_INSECURE_HTTP:-false}
    networks:
      default: {}
      elastic_default: {}
    restart: always

######################################################################################
######################################################################################
######################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
  elastic_default:
    external:
      name: ${ELASTICSEARCH_NETWORK_NAME:-elastic_default}
