---
version: "3.8"

services:
  ######################################################################################
  ######################################################################################
  ######################################################################################
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:${VERSION:-8.2.0}
    env_file: .env
    user: root
    hostname: elastic-agent
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.docker.network=proxy

        - traefik.http.routers.elastic-agent.entrypoints=elastic-agent
        - traefik.http.routers.elastic-agent.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.elastic-agent.tls=true
        - traefik.http.routers.elastic-agent.service=elastic-agent
        - traefik.http.services.elastic-agent.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.elastic-agent.loadbalancer.server.port=${PORT:-8220}
        - traefik.http.routers.elastic-agent.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    # ports:
    #   - target: 8220
    #     published: 8220
    #     mode: host
    configs:
      - source: agent_config
        target: /usr/share/elastic-agent/elastic-agent.yml
        mode: 0440
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/usr/share/elastic-agent

      # - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      # - /proc:/hostfs/proc:ro
      # - /:/hostfs:ro
      # - /var/log:/var/log:rw
    environment:
      ES_JAVA_OPTS: -Xms${ELK_MEM_USE_GB:-1g} -Xmx${ELK_MEM_USE_GB:-1g}
      network.host: 0.0.0.0

      FLEET_SERVER_ENABLE: ${FLEET_SERVER_ENABLE:-true}
      FLEET_SERVER_ELASTICSEARCH_HOST: ${ELASTICSEARCH_PROTOCOL:-https}://${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      # FLEET_SERVER_SERVICE_TOKEN: ${FLEET_SERVER_SERVICE_TOKEN}
      # FLEET_SERVER_POLICY: ${FLEET_SERVER_POLICY}
      FLEET_SERVER_INSECURE_HTTP: ${FLEET_SERVER_INSECURE_HTTP:-false}
    networks:
      # default: {}
      proxy: {}
      elasticsearch: {}
    restart: always

######################################################################################
######################################################################################
######################################################################################
networks:
  # default:
  #   name: elastic-agent
  #   driver: ${NETWORK_MODE:-bridge}
  #   attachable: true
  proxy:
    external: true
  elasticsearch:
    name: ${ELASTICSEARCH_NETWORK_NAME:-elasticsearch}
    external: true

volumes:
  data: {}

configs:
  agent_config:
    file: $PWD/config/elastic-agent.yml
