---
version: "3.8"

services:
  ######################################################################################
  ######################################################################################
  ######################################################################################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-7.14.1}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE}"
      restart_policy:
        condition: on-failure
    # ports:
    #   - target: 9200
    #     published: 9200
    #     mode: host
    #   - target: 9300
    #     published: 9300
    #     mode: host
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: -Xms${ELASTICSEARCH_MEM_USE_GB:-3g} -Xmx${ELASTICSEARCH_MEM_USE_GB:-3g}
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      discovery.type: ${DISCOVERY_TYPE:-single-node}
      bootstrap.memory_lock: ${MEMORY_LOCK:-true}
      # TAKE_FILE_OWNERSHIP: 1
      xpack.monitoring.collection.enabled: ${ELASTICSEARCH_ACTIVATE_SECURITY:-true}
      xpack.security.audit.enabled: ${ELASTICSEARCH_ACTIVATE_SECURITY:-true}
      xpack.license.self_generated.type: ${ELASTICSEARCH_LICENSE_TYPE:-trial} # basic | trial
      xpack.security.enabled: ${ELASTICSEARCH_ACTIVATE_SECURITY:-true}
      xpack.security.authc.api_key.enabled: ${ELASTICSEARCH_ACTIVATE_SECURITY}
      network.host: 0.0.0.0
    networks:
      default: {}
    restart: always

######################################################################################
######################################################################################
######################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}

volumes:
  elasticsearch: {}
