---
version: "3.8"

services:
  ######################################################################################
  ######################################################################################
  ######################################################################################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-8.0.0}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.docker.network=proxy
        - traefik.http.routers.elasticsearch.entrypoints=https
        - traefik.http.routers.elasticsearch.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.elasticsearch.tls=true
        - traefik.http.routers.elasticsearch.service=elasticsearch
        - traefik.http.services.elasticsearch.loadbalancer.server.scheme=${PROTOCOL:-https}
        - traefik.http.services.elasticsearch.loadbalancer.server.port=${PORT:-9200}
        - traefik.http.routers.elasticsearch.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    # ports:
    #   - target: 9200
    #     published: 9200
    #     protocol: tcp
    #     mode: host
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    configs:
      # - source: config_file
      #   target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: pw_file
        target: ${ELASTIC_PASSWORD_FILE:-/run/secrets/bootstrapPassword.txt}
        mode: 0400
        uid: "1000"
        gid: "1000"
      - source: ssl_key
        target: /usr/share/elasticsearch/config/${XPACK_SECURITY_TRANSPORT_SSL_KEY:-certs/elasticsearch_node.key}
      - source: ssl_certificate
        target: /usr/share/elasticsearch/config/${XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE:-certs/elasticsearch_node.crt}
    environment:
      ES_JAVA_OPTS: -Xms${ELK_MEM_USE_GB:-3g} -Xmx${ELK_MEM_USE_GB:-3g}
      ELASTIC_PASSWORD_FILE: ${ELASTIC_PASSWORD_FILE:-/run/secrets/bootstrapPassword.txt}
      network.host: ${NETWORK_HOST:-0.0.0.0}
      discovery.type: ${DISCOVERY_TYPE:-single-node}
      node.name: ${NODE_NAME:-elasticsearch-docker-default-1}
      cluster.name: ${CLUSTER_NAME:-elasticsearch-docker-cluster}
      bootstrap.memory_lock: ${BOOTSTRAP_MEMORY_LOCK:-true}
      node.store.allow_mmap: ${NODE_STORE_ALLOW_MMAP:-false}
      ingest.geoip.downloader.enabled: ${INGEST_GEOIP_DOWNLOADER_ENABLED:-true}
      xpack.security.enabled: ${XPACK_SECURITY_ENABLED:-true}
      xpack.security.transport.ssl.enabled: ${XPACK_SECURITY_TRANSPORT_SSL_ENABLED:-true}
      xpack.security.http.ssl.enabled: ${XPACK_SECURITY_HTTP_SSL_ENABLED:-true}
      xpack.security.authc.token.enabled: ${XPACK_SECURITY_AUTHC_TOKEN_ENABLED:-true}
      xpack.security.audit.enabled: ${XPACK_SECURITY_AUDIT_ENABLED:-true}
      xpack.security.authc.realms.file.file1.order: ${XPACK_SECURITY_AUTHC_REALMS_FILE_FILE1_ORDER:-0}
      xpack.security.authc.realms.native.native1.order: ${XPACK_SECURITY_AUTHC_REALMS_NATIVE_NATIVE1_ORDER:-1}
      xpack.security.authc.api_key.enabled: ${XPACK_SECURITY_AUTHC_API_KEY_ENABLED:-true}
      xpack.security.http.ssl.key: ${XPACK_SECURITY_HTTP_SSL_KEY:-certs/elasticsearch_node.key}
      xpack.security.http.ssl.certificate: ${XPACK_SECURITY_HTTP_SSL_CERTIFICATE:-certs/elasticsearch_node.crt}
      xpack.security.transport.ssl.key: ${XPACK_SECURITY_TRANSPORT_SSL_KEY:-certs/elasticsearch_node.key}
      xpack.security.transport.ssl.certificate: ${XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE:-certs/elasticsearch_node.crt}
      xpack.http.ssl.verification_mode: ${XPACK_HTTP_SSL_VERIFICATION_MODE:-certificate}
      xpack.security.http.ssl.verification_mode: ${XPACK_SECURITY_HTTP_SSL_VERIFICATION_MODE:-certificate}
      xpack.security.transport.ssl.verification_mode: ${XPACK_SECURITY_TRANSPORT_SSL_VERIFICATION_MODE:-certificate}
      xpack.license.self_generated.type: ${XPACK_LICENSE_SELF_GENERATED_TYPE:-basic}
      action.destructive_requires_name: ${ACTION_DESTRUCTIVE_REQUIRES_NAME:-false}
    networks:
      default: {}
      proxy: {}
    restart: always
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s ${PROTOCOL:-https}://localhost:9200/_cluster/health | grep -vq '"status":"red"'

######################################################################################
######################################################################################
######################################################################################
networks:
  default:
    name: elasticsearch
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
  proxy:
    external: true

volumes:
  elasticsearch: {}

configs:
  # config_file:
  #   file: $PWD/config/elasticsearch.yml
  pw_file:
    file: $PWD/config/bootstrapPassword.txt
  ssl_key:
    file: $PWD/config/ssl/elasticsearch_node.key
  ssl_certificate:
    file: $PWD/config/ssl/elasticsearch_node.crt
