# Module: auditd
# Docs: https://www.elastic.co/guide/en/beats/filebeat/8.5/filebeat-module-auditd.html

- module: auditd
  log:
    enabled: true
    var.paths:
      - /host/log/audit/audit.log*
    exclude_files:
      - \.gz$
