# Default Kibana configuration for docker target
server.host: "0.0.0.0"
server.shutdownTimeout: "5s"

elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: ""

xpack.reporting.encryptionKey: "<ADD_HERE (32_characters)>"
xpack.security.encryptionKey: "<ADD_HERE (32_characters)>"
xpack.encryptedSavedObjects.encryptionKey: "<ADD_HERE (32_characters)>"

elasticsearch.ssl.verificationMode: none

server.ssl.enabled: true
server.ssl.key: /usr/share/kibana/config/certs/kibana_node.key
server.ssl.certificate: /usr/share/kibana/config/certs/kibana_node.crt

monitoring.ui.container.elasticsearch.enabled: true
xpack.task_manager.monitored_stats_health_verbose_log.enabled: true
xpack.reporting.roles.enabled: false
xpack.reporting.kibanaServer.hostname: localhost
