---
version: "3.8"

services:
  ######################################################################################
  ######################################################################################
  ######################################################################################
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTICSEARCH_VERSION:-7.14.1}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE}"
      restart_policy:
        condition: on-failure
    ports:
      - target: 5040
        published: 5040
        mode: host
      - target: 5044
        published: 5044
        mode: host
      - target: 5190
        published: 5190
        mode: host
      - target: 9600
        published: 9600
        mode: host
      - target: 5140
        published: 5140
        mode: host
        protocol: udp
      - target: 5141
        published: 5141
        mode: host
        protocol: udp
    volumes:
      - ./config/pfelk/conf.d/:/etc/pfelk/conf.d:ro
      - ./config/pfelk/patterns/:/etc/pfelk/patterns:ro
      - ./config/pfelk/databases/:/etc/pfelk/databases:ro
    configs:
      # - source: ls_logstash_config
      #   target: /usr/share/logstash/config/logstash.yml
      - source: ls_pipelines_config
        target: /usr/share/logstash/config/pipelines.yml
    environment:
      CONFIG_RELOAD_AUTOMATIC: ${LOGSTAST_RELOAD_AUTOMATIC:-true}
      ES_JAVA_OPTS: -Xms${LOGSTAST_MEM_USE_GB:-2g} -Xmx${LOGSTAST_MEM_USE_GB:-2g}
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_PROTOCOL:-http}://${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME:-elastic}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_PROTOCOL:-http}://${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      XPACK_MONITORING_ELASTICSEARCH_URL: ${ELASTICSEARCH_PROTOCOL:-http}://${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME:-elastic}
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      xpack.monitoring.enabled: ${XPACK_MONITORING_ENABLED:-true}
      xpack.monitoring.elasticsearch.hosts: ${ELASTICSEARCH_PROTOCOL:-http}://${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      xpack.monitoring.elasticsearch.username: ${ELASTICSEARCH_USERNAME:-elastic}
      xpack.monitoring.elasticsearch.password: ${ELASTICSEARCH_PASSWORD}

    networks:
      default: {}
      elastic_default: {}
    restart: unless-stopped

######################################################################################
######################################################################################
######################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
  elastic_default:
    external:
      name: ${ELASTICSEARCH_NETWORK_NAME:-elastic_default}

configs:
  # ls_logstash_config:
  #   file: $PWD/config/logstash/config/logstash.yml
  ls_pipelines_config:
    file: $PWD/config/logstash/config/pipelines.yml
