---
version: "3.8"

services:
  ######################################################################################
  ######################################################################################
  ######################################################################################
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTICSEARCH_VERSION:-8.0.0}
    env_file: .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
    ports:
      # - target: 5040 # suricata
      #   published: 5040
      #   mode: host
      # - target: 5044 # beats
      #   published: 5044
      #   mode: host
      # - target: 5190 # haproxy
      #   published: 5190
      #   mode: host
      # - target: 9600 # general information about the Logstash
      #   published: 9600
      #   mode: host
      #   protocol: tcp
      - target: 5140 # firewall-1 (opnsense)
        published: 5140
        mode: host
        protocol: udp
      # - target: 5141
      #   published: 5141 # firewall-2 (pfSense)
      #   mode: host
      #   protocol: udp
    volumes:
      - ./config/pfelk/conf.d/:/etc/pfelk/conf.d:ro
      - ./config/pfelk/patterns/:/etc/pfelk/patterns:ro
      - ./config/pfelk/databases/:/etc/pfelk/databases:ro
    configs:
      # - source: ls_logstash_config
      #   target: /usr/share/logstash/config/logstash.yml
      - source: ls_pipelines_config
        target: /usr/share/logstash/config/pipelines.yml
    environment:
      ES_JAVA_OPTS: -Xms${ELK_MEM_USE_GB:-2g} -Xmx${ELK_MEM_USE_GB:-2g}
      network.host: 0.0.0.0
      CONFIG_RELOAD_AUTOMATIC: ${LOGSTAST_RELOAD_AUTOMATIC:-true}
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_PROTOCOL:-https}://${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME:-logstash_system}
      ELASTICSEARCH_SSL_VERIFICATIONMODE: ${ELASTICSEARCH_SSL_VERIFICATIONMODE:-none}
      xpack.monitoring.enabled: ${XPACK_MONITORING_ENABLED:-true}
      xpack.monitoring.elasticsearch.hosts: ${ELASTICSEARCH_PROTOCOL:-https}://${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      xpack.monitoring.elasticsearch.username: ${ELASTICSEARCH_USERNAME:-logstash_system}
    networks:
      default: {}
      elasticsearch: {}
    restart: always

######################################################################################
######################################################################################
######################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
  elasticsearch:
    external:
      name: ${ELASTICSEARCH_NETWORK_NAME:-elasticsearch}

configs:
  # ls_logstash_config:
  #   file: $PWD/config/logstash/config/logstash.yml
  ls_pipelines_config:
    file: $PWD/config/logstash/config/pipelines.yml
